AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FileName:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Encoding:
  Enabled: false

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 100
